Repository gamenome-project/gamenome-project-server, pull requests merged in 2024-05, with the labels that each got.

#22 V1 Api Mapping Config 추가
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/ApiV1MappingConfig.kt
Labels: enhancement

#23 #5 ModelNotFoundException을 핸들링하는 Global exception handler 추가
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/exception/GlobalExceptionHandler.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/exception/ModelNotFoundException.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/exception/dto/ErrorDto.kt
Labels: enhancement

#24 #4 Swagger Config 추가
  build.gradle.kts
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/infra/swagger/SwaggerConfig.kt
Labels: documentation

#25 #17 Supabase ignore / 의존성 설정
  .gitignore
  build.gradle.kts
Labels: documentation, enhancement

#32 #3 신고 기능 뼈대 추가 & 기능 설명
  .gitignore
  bin/main/application.properties
  build.gradle.kts
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/controller/v1/CommentController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/dto/v1/CommentReportResponseDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/dto/v1/ReportCommentRequestDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/service/v1/CommentService.kt
  src/main/resources/application.properties
Labels: enhancement

#35 #21 Comment entity import, API V1 Mapping 정상 작동 안되는 문제 해결
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/ApiV1MappingConfig.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/controller/v1/CommentController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/entity/Comment.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/review/controller/v1/ReviewController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/controller/v1/UserController.kt
Labels: bug

#40 #39 User 명세에 한 줄 소개, 프로필 이미지 URL 추가
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/dto/UserDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/dto/UserUpdateProfileDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/model/Profile.kt
Labels: enhancement

#42 #7 User domain 기본 비즈니스 로직 작성
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/controller/v1/UserController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/dto/SignUpDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/dto/UserDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/model/User.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/repository/UserRepository.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/service/v1/UserService.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/service/v1/UserServiceImpl.kt
Labels: enhancement

#41 #8 Comment Domain 로직 작성하기
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/dto/v1/CommentResponseDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/dto/v1/CreateCommentRequestDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/entity/v1/Comment.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/repository/CommentRepository.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/repository/v1/CommentRepository.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/service/v1/CommentService.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/review/controller/v1/ReviewController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/controller/v1/UserController.kt
Labels: enhancement

#46 #9 JWT 발급 유틸리티 추가 및 로그인시 AccessToken 반환
  build.gradle.kts
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/GamenomeProjectServerApplication.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/dto/v1/CreateCommentRequestDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/security/jwt/JwtPlugin.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/security/jwt/JwtProperties.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/security/jwt/JwtResponseDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/controller/v1/UserController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/service/v1/UserService.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/service/v1/UserServiceImpl.kt
Labels: enhancement

#49 #12 리뷰 신고 및 조회 로직 추가
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/report/entity/v1/Report.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/report/repository/v1/ReportRepository.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/report/service/ReportService.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/review/dto/v1/ReviewReportDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/review/service/v1/ReviewServiceImpl.kt
Labels: enhancement

#52 #47 Entity String 명시적으로 VARCHAR / TEXT 구분
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/entity/v1/Comment.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/report/entity/v1/Report.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/review/model/v1/Review.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/model/Profile.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/model/User.kt
Labels: enhancement

#56 #55 user service jwt 정상적으로 userId 반환하게 수정
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/controller/v1/UserController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/service/v1/UserServiceImpl.kt
Labels: bug

#54 #31 댓글 신고 로직 작성
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/dto/v1/CommentReportResponseDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/dto/v1/ReportCommentRequestDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/service/v1/CommentService.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/report/service/ReportService.kt
Labels: enhancement

#60 Feat: #13 패스워드 암호화 설정 및 Spring security 기본 로그인 disable 설정
  build.gradle.kts
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/security/jwt/SecurityConfig.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/service/v1/UserServiceImpl.kt
Labels: enhancement

#68 #29 review pagenation 진행
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/etc/CommentSort.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/review/controller/v1/ReviewController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/review/etc/ReviewSort.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/review/repository/v1/ReviewRepository.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/review/service/v1/ReviewService.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/review/service/v1/ReviewServiceImpl.kt
Labels: enhancement

#67 #66 Comment에 SoftDelete 추가
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/entity/v1/Comment.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/service/v1/CommentService.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/reaction/service/v1/ReactionService.kt
Labels: enhancement

#71 #57 Swagger header Authorization 추가
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/controller/v1/UserController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/infra/swagger/SwaggerConfig.kt
Labels: enhancement

#80 #27 이메일 인증 및 닉네임 중복 확인 기능
  build.gradle.kts
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/common/utils/RedisUtils.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/common/utils/Secret.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/controller/v1/UserController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/dto/SendMailResponse.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/repository/UserRepository.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/service/v1/UserService.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/service/v1/UserServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/infra/redis/RedisConfig.kt
Labels: enhancement

#77 User Following 기능 구현
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/comment/dto/v1/GetCommentResponseDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/follow/controller/v1/FollowController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/follow/dto/v1/FollowingRequestDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/follow/dto/v1/FollowingResponseDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/follow/dto/v1/FollowingUser.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/follow/model/v1/Follow.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/follow/model/v1/FollowId.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/follow/repository/v1/FollowRepository.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/follow/service/v1/FollowService.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/model/User.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/exception/DuplicatedException.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/exception/GlobalExceptionHandler.kt
Labels: enhancement

#92 Feat: #37 프로필 이미지 저장 구현
  build.gradle.kts
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/common/utils/S3FileManagement.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/s3/service/v1/S3Service.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/s3/service/v1/S3ServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/controller/v1/UserController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/dto/UserUpdateProfileDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/model/User.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/service/v1/UserService.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/service/v1/UserServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/exception/FileValidateException.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/exception/GlobalExceptionHandler.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/infra/s3/S3Config.kt
Labels: enhancement

#91 #38 Kakao Oauth 로그인 구현
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/dto/SignUpDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/model/User.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/oauth/OAuthKakaoConfig.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/oauth/OAuthKakaoController.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/oauth/OAuthKakaoToken.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/oauth/dto/OAuthKakaoCreateDto.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/repository/UserJpaRepository.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/repository/UserRepository.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/repository/UserRepositoryImpl.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/service/v1/UserService.kt
  src/main/kotlin/sparta/nbcamp/gamenomeprojectserver/domain/user/service/v1/UserServiceImpl.kt
Labels: enhancement
